name: Release

on:
  release:
    types: [published]

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yonote:${{ github.ref_name }}
      - name: Update release notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ github.event.release.body }}

            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/yonote:${{ github.ref_name }}
            ```
