name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: yonote-linux
            ext: ""
          - os: macos-latest
            artifact: yonote-macos
            ext: ""
          - os: windows-latest
            artifact: yonote-windows.exe
            ext: ".exe"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller yonote_cli/yonote_cli/__main__.py --name yonote --onefile
          mkdir release
          mv dist/yonote${{ matrix.ext }} release/${{ matrix.artifact }}
        shell: bash
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/${{ matrix.artifact }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yonote:${{ github.ref_name }}
