name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/yonote:${{ github.ref_name }}
      - name: Update release notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ github.event.release.body }}

            ```bash
            docker pull ghcr.io/${{ github.repository_owner }}/yonote:${{ github.ref_name }}
            ```

  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
      - name: Update README with tag
        run: |
          latest_tag="${GITHUB_REF#refs/tags/}"
          sed -i "s/^export YONOTE_VERSION=.*/export YONOTE_VERSION=${latest_tag}/" README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "docs: update README for ${latest_tag}" && git push
